name: My Custom Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start workflow message
        run: echo "Now running build workflow."

      # Your existing steps go here...

      - name: Ending workflow message
        run: |
          echo "Now ending build workflow."
          echo "Have a great day!"

      # Add the completion message step
      - name: Completion message
        if: always()  # This ensures the step runs even if previous steps fail
        run: echo "Action Complete!"
